# https://www.home-assistant.io/lovelace/
# https://materialdesignicons.com/tag/community

title: Умный дом

views:
  - !include includes/lovelace/home.yaml
  - !include includes/lovelace/info.yaml
  - !include includes/lovelace/camera.yaml
  - !include includes/lovelace/lan.yaml
  - !include includes/lovelace/control.yaml
  - !include includes/lovelace/powercount.yaml
  - !include includes/lovelace/battery.yaml
  - !include includes/lovelace/develop.yaml
  